version: '3.1'

services:

  frontend:
    container_name: frontend
    build: .
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 4100:4100
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

